### ISSUE TITLE
Can´t get past Logging in using Google

### ISSUE THREAD

**Issue by MasterOfFight** [NECROBOTIO/NecroBot#4303]
Hello Guy´s,

I just downloaded the newest version (was offline for a couple of day´s, so my old version was 0.7.6 I think) and with this new version it is not starting up at all.

I tryed with a fresh download too.
I get the following text:

Perfext! You already have the newest Version 0.8.2
Loggin in using Google
Your IP is: xxxxxxxxxxx

Than it loads for 2-3 minutes and it gives me a message as shown in the LOG

[NecroBot-2016-08-10-08.txt](https://github.com/NECROBOTIO/NecroBot/files/410421/NecroBot-2016-08-10-08.txt)

I hope somebody can help me.

Thanks in advance

**Comment by nakuma85** [comment]
It's just down. I have the same issue.

**Comment by Marsupilami73** [comment]
The path in the log file is wrong!
"C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:Zeile 98."
Seems to be also a compiling error?
Same in my log file.

I overwrote the 8.2 necrobot exe with the downloaded one and it seems to work again.

Best wishes
Marsipulami

**Comment by jazzu20** [comment]
1. delete the folder (release.zip)
2. re extract the zip file (release.zip)
3. run the program. and update.
4. it should be working now

**Comment by Marsupilami73** [comment]
Hi, did you correct also the path?
Seems that path variables may forgotten?

There are some full path settings to find.

Best wishes
Marsipulami

**Comment by Marsupilami73** [comment]
thx for the quick fix!

2016-08-10 8:35 GMT+02:00 jazzu20 <notifications@github.com>:

**Comment by MasterOfFight** [comment]
Deletet all folders and made a clean reinstall and download with 0.8.3

But I still get the same issue (or another?) I will provide the Log here too.
[NecroBot-2016-08-10-09.txt](https://github.com/NECROBOTIO/NecroBot/files/410493/NecroBot-2016-08-10-09.txt)

**Comment by MasterOfFight** [comment]
Same problem with 0.8.4... :(

**Comment by kasabians** [comment]
Same problem for me
